# GitHub colours from bat's bundled theme.
[color]
depth = 24

[color.ansi16]
same = { color = "black", bgcolor = "default", bold = false, italic = false }
line_number = { color = "black", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "black", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "black", bgcolor = "default", bold = false, italic = false }
omitted = { color = "bright_black", bgcolor = "default", bold = false, italic = false }
add = { color = "blue", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "bright_white", bgcolor = "blue", bold = true, italic = false }
remove = { color = "cyan", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "bright_white", bgcolor = "cyan", bold = true, italic = false }
overlap_highlight = { color = "bright_white", bgcolor = "magenta", bold = true, italic = false }
syntax_comment = { color = "bright_black", bold = false, italic = false }
syntax_comment_highlight = { color = "bright_white", bold = false, italic = false }
syntax_keyword = { color = "magenta", bold = false, italic = false }
syntax_keyword_highlight = { color = "bright_white", bold = false, italic = false }
syntax_string = { color = "blue", bold = false, italic = false }
syntax_string_highlight = { color = "bright_white", bold = false, italic = false }
syntax_number = { color = "cyan", bold = false, italic = false }
syntax_number_highlight = { color = "bright_white", bold = false, italic = false }
syntax_definition = { color = "bright_black", bold = false, italic = false }
syntax_definition_highlight = { color = "bright_white", bold = false, italic = false }

[color.ansi256]
same = { color = 236, bgcolor = "default", bold = false, italic = false }
line_number = { color = 236, bgcolor = "default", bold = false, italic = false }
line_number_add = { color = 236, bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = 236, bgcolor = "default", bold = false, italic = false }
omitted = { color = 246, bgcolor = "default", bold = false, italic = false }
add = { color = 24, bgcolor = "default", bold = true, italic = false }
add_highlight = { color = 15, bgcolor = 24, bold = true, italic = false }
remove = { color = 31, bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = 15, bgcolor = 31, bold = true, italic = false }
overlap_highlight = { color = 15, bgcolor = 125, bold = true, italic = false }
syntax_comment = { color = 246, bold = false, italic = false }
syntax_comment_highlight = { color = 15, bold = false, italic = false }
syntax_keyword = { color = 125, bold = false, italic = false }
syntax_keyword_highlight = { color = 15, bold = false, italic = false }
syntax_string = { color = 24, bold = false, italic = false }
syntax_string_highlight = { color = 15, bold = false, italic = false }
syntax_number = { color = 31, bold = false, italic = false }
syntax_number_highlight = { color = 15, bold = false, italic = false }
syntax_definition = { color = 97, bold = false, italic = false }
syntax_definition_highlight = { color = 15, bold = false, italic = false }

[color.truecolor]
same = { color = "#333333", bgcolor = "default", bold = false, italic = false }
line_number = { color = "#333333", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "#333333", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "#333333", bgcolor = "default", bold = false, italic = false }
omitted = { color = "#969896", bgcolor = "default", bold = false, italic = false }
add = { color = "#183691", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "#ffffff", bgcolor = "#183691", bold = true, italic = false }
remove = { color = "#0086b3", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "#ffffff", bgcolor = "#0086b3", bold = true, italic = false }
overlap_highlight = { color = "#ffffff", bgcolor = "#a71d5d", bold = true, italic = false }
syntax_comment = { color = "#969896", bold = false, italic = false }
syntax_comment_highlight = { color = "#ffffff", bold = false, italic = false }
syntax_keyword = { color = "#a71d5d", bold = false, italic = false }
syntax_keyword_highlight = { color = "#ffffff", bold = false, italic = false }
syntax_string = { color = "#183691", bold = false, italic = false }
syntax_string_highlight = { color = "#ffffff", bold = false, italic = false }
syntax_number = { color = "#0086b3", bold = false, italic = false }
syntax_number_highlight = { color = "#ffffff", bold = false, italic = false }
syntax_definition = { color = "#795da3", bold = false, italic = false }
syntax_definition_highlight = { color = "#ffffff", bold = false, italic = false }
