# OneHalfLight colours from bat's bundled theme.
[color]
depth = 24

[color.ansi16]
same = { color = "blue", bgcolor = "default", bold = false, italic = false }
line_number = { color = "white", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "white", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "white", bgcolor = "default", bold = false, italic = false }
omitted = { color = "white", bgcolor = "default", bold = false, italic = false }
add = { color = "bright_black", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "bright_white", bgcolor = "bright_black", bold = true, italic = false }
remove = { color = "yellow", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "bright_white", bgcolor = "yellow", bold = true, italic = false }
overlap_highlight = { color = "bright_white", bgcolor = "magenta", bold = true, italic = false }
syntax_comment = { color = "white", bold = false, italic = false }
syntax_comment_highlight = { color = "bright_white", bold = false, italic = false }
syntax_keyword = { color = "magenta", bold = false, italic = false }
syntax_keyword_highlight = { color = "bright_white", bold = false, italic = false }
syntax_string = { color = "bright_black", bold = false, italic = false }
syntax_string_highlight = { color = "bright_white", bold = false, italic = false }
syntax_number = { color = "yellow", bold = false, italic = false }
syntax_number_highlight = { color = "bright_white", bold = false, italic = false }
syntax_definition = { color = "cyan", bold = false, italic = false }
syntax_definition_highlight = { color = "bright_white", bold = false, italic = false }

[color.ansi256]
same = { color = 237, bgcolor = "default", bold = false, italic = false }
line_number = { color = 188, bgcolor = "default", bold = false, italic = false }
line_number_add = { color = 188, bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = 188, bgcolor = "default", bold = false, italic = false }
omitted = { color = 247, bgcolor = "default", bold = false, italic = false }
add = { color = 71, bgcolor = "default", bold = true, italic = false }
add_highlight = { color = 15, bgcolor = 71, bold = true, italic = false }
remove = { color = 136, bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = 15, bgcolor = 136, bold = true, italic = false }
overlap_highlight = { color = 15, bgcolor = 127, bold = true, italic = false }
syntax_comment = { color = 247, bold = false, italic = false }
syntax_comment_highlight = { color = 15, bold = false, italic = false }
syntax_keyword = { color = 127, bold = false, italic = false }
syntax_keyword_highlight = { color = 15, bold = false, italic = false }
syntax_string = { color = 71, bold = false, italic = false }
syntax_string_highlight = { color = 15, bold = false, italic = false }
syntax_number = { color = 136, bold = false, italic = false }
syntax_number_highlight = { color = 15, bold = false, italic = false }
syntax_definition = { color = 31, bold = false, italic = false }
syntax_definition_highlight = { color = 15, bold = false, italic = false }

[color.truecolor]
same = { color = "#383a42", bgcolor = "default", bold = false, italic = false }
line_number = { color = "#d4d4d4", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "#d4d4d4", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "#d4d4d4", bgcolor = "default", bold = false, italic = false }
omitted = { color = "#a0a1a7", bgcolor = "default", bold = false, italic = false }
add = { color = "#50a14f", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "#fafafa", bgcolor = "#50a14f", bold = true, italic = false }
remove = { color = "#c18401", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "#fafafa", bgcolor = "#c18401", bold = true, italic = false }
overlap_highlight = { color = "#fafafa", bgcolor = "#a626a4", bold = true, italic = false }
syntax_comment = { color = "#a0a1a7", bold = false, italic = false }
syntax_comment_highlight = { color = "#fafafa", bold = false, italic = false }
syntax_keyword = { color = "#a626a4", bold = false, italic = false }
syntax_keyword_highlight = { color = "#fafafa", bold = false, italic = false }
syntax_string = { color = "#50a14f", bold = false, italic = false }
syntax_string_highlight = { color = "#fafafa", bold = false, italic = false }
syntax_number = { color = "#c18401", bold = false, italic = false }
syntax_number_highlight = { color = "#fafafa", bold = false, italic = false }
syntax_definition = { color = "#0184bc", bold = false, italic = false }
syntax_definition_highlight = { color = "#fafafa", bold = false, italic = false }
