# Sublime Snazzy colours from bat's bundled theme.
[color]
depth = 24

[color.ansi16]
same = { color = "bright_white", bgcolor = "default", bold = false, italic = false }
line_number = { color = "bright_white", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "bright_white", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "bright_white", bgcolor = "default", bold = false, italic = false }
omitted = { color = "bright_black", bgcolor = "default", bold = false, italic = false }
add = { color = "white", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "black", bgcolor = "white", bold = true, italic = false }
remove = { color = "bright_white", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "black", bgcolor = "bright_white", bold = true, italic = false }
overlap_highlight = { color = "black", bgcolor = "white", bold = true, italic = false }
syntax_comment = { color = "bright_black", bold = false, italic = false }
syntax_comment_highlight = { color = "black", bold = false, italic = false }
syntax_keyword = { color = "white", bold = false, italic = true }
syntax_keyword_highlight = { color = "black", bold = false, italic = true }
syntax_string = { color = "white", bold = false, italic = false }
syntax_string_highlight = { color = "black", bold = false, italic = false }
syntax_number = { color = "bright_white", bold = false, italic = false }
syntax_number_highlight = { color = "black", bold = false, italic = false }
syntax_definition = { color = "white", bold = false, italic = false }
syntax_definition_highlight = { color = "black", bold = false, italic = false }

[color.ansi256]
same = { color = 255, bgcolor = "default", bold = false, italic = false }
line_number = { color = 255, bgcolor = "default", bold = false, italic = false }
line_number_add = { color = 255, bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = 255, bgcolor = "default", bold = false, italic = false }
omitted = { color = 242, bgcolor = "default", bold = false, italic = false }
add = { color = 229, bgcolor = "default", bold = true, italic = false }
add_highlight = { color = 236, bgcolor = 229, bold = true, italic = false }
remove = { color = 255, bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = 236, bgcolor = 255, bold = true, italic = false }
overlap_highlight = { color = 236, bgcolor = 123, bold = true, italic = false }
syntax_comment = { color = 242, bold = false, italic = false }
syntax_comment_highlight = { color = 236, bold = false, italic = false }
syntax_keyword = { color = 123, bold = false, italic = true }
syntax_keyword_highlight = { color = 236, bold = false, italic = true }
syntax_string = { color = 229, bold = false, italic = false }
syntax_string_highlight = { color = 236, bold = false, italic = false }
syntax_number = { color = 255, bold = false, italic = false }
syntax_number_highlight = { color = 236, bold = false, italic = false }
syntax_definition = { color = 123, bold = false, italic = false }
syntax_definition_highlight = { color = 236, bold = false, italic = false }

[color.truecolor]
same = { color = "#f8f8f2", bgcolor = "default", bold = false, italic = false }
line_number = { color = "#f8f8f2", bgcolor = "default", bold = false, italic = false }
line_number_add = { color = "#f8f8f2", bgcolor = "default", bold = false, italic = false }
line_number_remove = { color = "#f8f8f2", bgcolor = "default", bold = false, italic = false }
omitted = { color = "#686868", bgcolor = "default", bold = false, italic = false }
add = { color = "#f3f99d", bgcolor = "default", bold = true, italic = false }
add_highlight = { color = "#282a36", bgcolor = "#f3f99d", bold = true, italic = false }
remove = { color = "#f1f1f0", bgcolor = "default", bold = true, italic = false }
remove_highlight = { color = "#282a36", bgcolor = "#f1f1f0", bold = true, italic = false }
overlap_highlight = { color = "#282a36", bgcolor = "#9aedfe", bold = true, italic = false }
syntax_comment = { color = "#686868", bold = false, italic = false }
syntax_comment_highlight = { color = "#282a36", bold = false, italic = false }
syntax_keyword = { color = "#9aedfe", bold = false, italic = true }
syntax_keyword_highlight = { color = "#282a36", bold = false, italic = true }
syntax_string = { color = "#f3f99d", bold = false, italic = false }
syntax_string_highlight = { color = "#282a36", bold = false, italic = false }
syntax_number = { color = "#f1f1f0", bold = false, italic = false }
syntax_number_highlight = { color = "#282a36", bold = false, italic = false }
syntax_definition = { color = "#9aedfe", bold = false, italic = false }
syntax_definition_highlight = { color = "#282a36", bold = false, italic = false }
