# Twilight colours taken from Jon's dark Tilix terminal scheme.
[color]
depth = 256

[color.ansi16]
same = { color = "white", bgcolor = "default", bold = false }
line_number = { color = "white", bgcolor = "default", bold = true }
omitted = { color = "bright_black", bgcolor = "default", bold = false }
add = { color = "green", bgcolor = "default", bold = true }
add_highlight = { color = "black", bgcolor = "green", bold = true }
remove = { color = "red", bgcolor = "default", bold = true }
remove_highlight = { color = "black", bgcolor = "red", bold = true }
overlap_highlight = { color = "black", bgcolor = "yellow", bold = true }
syntax_comment = { color = "bright_black", bold = false }
syntax_comment_highlight = { color = "bright_black", bold = false }
syntax_keyword = { color = "magenta", bold = false }
syntax_keyword_highlight = { color = "magenta", bold = false }
syntax_string = { color = "green", bold = false }
syntax_string_highlight = { color = "green", bold = false }
syntax_number = { color = "red", bold = false }
syntax_number_highlight = { color = "red", bold = false }
syntax_definition = { color = "yellow", bold = false }
syntax_definition_highlight = { color = "yellow", bold = false }

[color.ansi256]
same = { color = 248, bgcolor = "default", bold = false }
line_number = { color = 248, bgcolor = "default", bold = true }
omitted = { color = 59, bgcolor = "default", bold = false }
add = { color = 107, bgcolor = "default", bold = true }
add_highlight = { color = 16, bgcolor = 107, bold = true }
remove = { color = 167, bgcolor = "default", bold = true }
remove_highlight = { color = 16, bgcolor = 167, bold = true }
overlap_highlight = { color = 16, bgcolor = 228, bold = true }
syntax_comment = { color = 59, bold = false }
syntax_comment_highlight = { color = 59, bold = false }
syntax_keyword = { color = 139, bold = false }
syntax_keyword_highlight = { color = 139, bold = false }
syntax_string = { color = 107, bold = false }
syntax_string_highlight = { color = 107, bold = false }
syntax_number = { color = 167, bold = false }
syntax_number_highlight = { color = 167, bold = false }
syntax_definition = { color = 228, bold = false }
syntax_definition_highlight = { color = 228, bold = false }
