language: rust
dist: jammy
rust: stable

cache:
  directories:
    - $HOME/.cache/uv
    - $HOME/.cargo/registry
    - $HOME/.cargo/git

before_install:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - export PATH="$HOME/.local/bin:$PATH"
  - rustup component add clippy rustfmt

install:
  - uv sync --locked

script:
  - uv run pre-commit run --all-files
  - cargo test
  - uv run python -m unittest discover -s python/tests
  - uv run python -m unittest discover -s jiff-configure/tests
  - uv run robot tests
