[package]
name = "jiff"
version = "0.1.0"
authors = ["jon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
term_size = "0.3"
clap = "~2.33.0"
difference = "~2.0.0"
itertools = "~0.8.1"
