[package]
name = "jiff"
version = "1.0.0"
description = "A terminal diff tool with sub-line and side-by-side output"
readme = "README.md"
authors = ["Jonathan Simmonds <jon@jonsim.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-ansi-term = "0.50.3"
termprofile = "0.2.4"
term_size = "0.3"
clap = "~2.33.0"
itertools = "~0.8.1"
syntect = { version = "5.3", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
unicode-width = "0.2.2"
unicode-segmentation = "1.13.3"
toml = "0.8"
