[project]
name = "jiff-dev-workspace"
version = "0.0.0"
readme = "README.md"
maintainers = [
    { name = "Jonathan Simmonds", email = "jon@jonsim.com" },
]
license = "MIT"

requires-python = ">=3.9"
dependencies = [
    "jiff",
    "jiff-configure",
]

[dependency-groups]
dev = [
    "pre-commit",
    "robotframework",
    "ruff==0.16.5",
]

[tool.uv]
package = false

[tool.uv.sources]
jiff = { workspace = true }
jiff-configure = { workspace = true }

[tool.uv.workspace]
members = ["python", "jiff-configure"]
