[project]
name = "jiff-dev"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "jiff",
    "jiff-configure",
]

[dependency-groups]
dev = [
    "pre-commit",
    "robotframework",
    "ruff==0.16.5",
]

[tool.uv]
package = false

[tool.uv.sources]
jiff = { workspace = true }
jiff-configure = { workspace = true }

[tool.uv.workspace]
members = ["python", "jiff-configure"]
