[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "jiff"
version = "1.0.0"
description = "A terminal diff tool with sub-line and side-by-side output"
maintainers = [
    { name = "Jonathan Simmonds", email = "jon@jonsim.com" },
]
license = "MIT"

requires-python = ">=3.9"
dependencies = [
    "pygments",
    "rich",
    "tomli; python_version < '3.11'",
]

[project.scripts]
jiff = "jiff:main"

[tool.setuptools]
py-modules = ["directory_diff", "jiff", "jiff_config", "jiff_version", "syntax_highlighting"]

[tool.setuptools.packages.find]
where = ["."]
include = ["diff"]
